require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CatchReportsController do

  # This should return the minimal set of attributes required to create a valid
  # CatchReport. As you add validations to CatchReport, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "description" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CatchReportsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all catch_reports as @catch_reports" do
      catch_report = CatchReport.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:catch_reports)).to eq([catch_report])
    end
  end

  describe "GET show" do
    it "assigns the requested catch_report as @catch_report" do
      catch_report = CatchReport.create! valid_attributes
      get :show, {:id => catch_report.to_param}, valid_session
      expect(assigns(:catch_report)).to eq(catch_report)
    end
  end

  describe "GET new" do
    it "assigns a new catch_report as @catch_report" do
      get :new, {}, valid_session
      expect(assigns(:catch_report)).to be_a_new(CatchReport)
    end
  end

  describe "GET edit" do
    it "assigns the requested catch_report as @catch_report" do
      catch_report = CatchReport.create! valid_attributes
      get :edit, {:id => catch_report.to_param}, valid_session
      expect(assigns(:catch_report)).to eq(catch_report)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CatchReport" do
        expect {
          post :create, {:catch_report => valid_attributes}, valid_session
        }.to change(CatchReport, :count).by(1)
      end

      it "assigns a newly created catch_report as @catch_report" do
        post :create, {:catch_report => valid_attributes}, valid_session
        expect(assigns(:catch_report)).to be_a(CatchReport)
        expect(assigns(:catch_report)).to be_persisted
      end

      it "redirects to the created catch_report" do
        post :create, {:catch_report => valid_attributes}, valid_session
        expect(response).to redirect_to(CatchReport.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved catch_report as @catch_report" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(CatchReport).to receive(:save).and_return(false)
        post :create, {:catch_report => { "description" => "invalid value" }}, valid_session
        expect(assigns(:catch_report)).to be_a_new(CatchReport)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(CatchReport).to receive(:save).and_return(false)
        post :create, {:catch_report => { "description" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested catch_report" do
        catch_report = CatchReport.create! valid_attributes
        # Assuming there are no other catch_reports in the database, this
        # specifies that the CatchReport created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(CatchReport).to receive(:update).with({ "description" => "MyText" })
        put :update, {:id => catch_report.to_param, :catch_report => { "description" => "MyText" }}, valid_session
      end

      it "assigns the requested catch_report as @catch_report" do
        catch_report = CatchReport.create! valid_attributes
        put :update, {:id => catch_report.to_param, :catch_report => valid_attributes}, valid_session
        expect(assigns(:catch_report)).to eq(catch_report)
      end

      it "redirects to the catch_report" do
        catch_report = CatchReport.create! valid_attributes
        put :update, {:id => catch_report.to_param, :catch_report => valid_attributes}, valid_session
        expect(response).to redirect_to(catch_report)
      end
    end

    describe "with invalid params" do
      it "assigns the catch_report as @catch_report" do
        catch_report = CatchReport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(CatchReport).to receive(:save).and_return(false)
        put :update, {:id => catch_report.to_param, :catch_report => { "description" => "invalid value" }}, valid_session
        expect(assigns(:catch_report)).to eq(catch_report)
      end

      it "re-renders the 'edit' template" do
        catch_report = CatchReport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(CatchReport).to receive(:save).and_return(false)
        put :update, {:id => catch_report.to_param, :catch_report => { "description" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested catch_report" do
      catch_report = CatchReport.create! valid_attributes
      expect {
        delete :destroy, {:id => catch_report.to_param}, valid_session
      }.to change(CatchReport, :count).by(-1)
    end

    it "redirects to the catch_reports list" do
      catch_report = CatchReport.create! valid_attributes
      delete :destroy, {:id => catch_report.to_param}, valid_session
      expect(response).to redirect_to(catch_reports_url)
    end
  end

end
